library("hamcrest")
require("benchmarkR")

assertThat(class(benchmarkR:::BenchmarkEnvironment), equalTo("environment"))
assertThat(class(benchmarkR:::ExecEnvironment), equalTo("environment"))
assertThat(class(benchGetter(target = 'profiles')), equalTo("data.frame"))
assertThat(class(benchGetter(target = 'benchmarks')), equalTo("data.frame"))
assertThat(class(benchGetter(target = 'meta')), equalTo("data.frame"))
assertThat(class(benchGetter(target = 'warnings')), equalTo("data.frame"))


assertThat(ncol(benchGetter(target = 'profiles')), equalTo(7))
assertThat(ncol(benchGetter(target = 'benchmarks')), equalTo(4))
assertThat(ncol(benchGetter(target = 'meta')), equalTo(3))
assertThat(ncol(benchGetter(target = 'warnings')), equalTo(3))

addP <- addProfiler()
assertTrue(is.null(addP))
dt <- data.frame(a=c(1,2),b=c(1,2))
addP <- addProfiler(dt)
assertTrue(is.null(addP))
dt <- data.frame(a=c(1,2),b=c(1,2),c=c(1,2),d=c(1,2))
addP <- addProfiler(dt)
assertTrue(is.null(addP))

pkg_installation <- installUsedPackages()
assertTrue(is.null(pkg_installation))
pkg_installation <- installUsedPackages(file = "./file/doesntExist.R")
assertTrue(is.null(pkg_installation))
pkg_installation <- installUsedPackages(file = "./test.R")
assertTrue(is.null(pkg_installation))
pkg_installation <- installUsedPackages(file = "./test3.R")
assertFalse(is.null(pkg_installation))


getterReturn <- benchGetter(target = "profile")
assertTrue(is.null(getterReturn))
getterReturn <- benchGetter(target = "profilerun")
assertTrue(is.null(getterReturn))
getterReturn <- class(benchGetter(target = "warnings"))
assertThat(getterReturn, equalTo("data.frame"))
getterReturn <- benchGetter(target = "usedpackages")
assertTrue(is.null(getterReturn))
getterReturn <- benchGetter(target = "usedpackages", file ="./test.R")
assertTrue(is.null(getterReturn))
getterReturn <- benchGetter(target = "usedpackages", file ="./jahkjad/kjasdksd.R")
assertTrue(is.null(getterReturn))

sysId = setSystemID()
assertFalse(is.null(sysId))
benchCleaner(target = "meta")
assertTrue(nrow(benchGetter(target = "meta")) == 0)

sysId <- benchGetter(target = "systemId")
print(sysId)
print(str(benchGetter(target = "profile", indexCol = "process", selectValue = "BENCHMARK", returnCol = "systemId")))
sysId_prf <- benchGetter(target = "profile", indexCol = "process", selectValue = "BENCHMARK", returnCol = "systemId")[1,1]
assertTrue(sysId == sysId_prf)

old_sysId <- benchGetter(target = "systemid")
assign("systemId", 666, envir = benchmarkR::ExecEnvironment)
setSystemID()
new_sysId <- benchGetter(target = "systemid")
assertTrue(nchar(new_sysId) == 18)
assertTrue(old_sysId != new_sysId)
assertTrue(new_sysId != 666)
